# Generated by Django 2.2.6 on 2020-03-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mega_juego',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
