# Generated by Django 2.2.6 on 2020-03-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mega_juego',
            name='categoria_pro',
            field=models.ManyToManyField(to='main.cate_Jueg', verbose_name='Categoria Producto'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='slug',
            field=models.SlugField(),
        ),
    ]
