# Generated by Django 2.2.6 on 2020-03-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mega_juego_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mega_juego',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
