# Generated by Django 2.2.6 on 2020-03-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200308_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mega_juego',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
