# Generated by Django 2.2.6 on 2020-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200309_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='mega_juego',
            name='cat_check',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
