# Generated by Django 2.2.6 on 2020-03-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mega_juego_cat_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mega_juego',
            name='cat_check',
        ),
    ]
