# Generated by Django 2.2.6 on 2020-03-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200309_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='mega_juego',
            name='enlace_publi2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad'),
        ),
        migrations.AddField(
            model_name='mega_juego',
            name='enlace_publi3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad'),
        ),
        migrations.AddField(
            model_name='mega_juego',
            name='enlacegd2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive'),
        ),
        migrations.AddField(
            model_name='mega_juego',
            name='enlacegd3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive'),
        ),
        migrations.AddField(
            model_name='mega_juego',
            name='enlacemg2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Mega'),
        ),
        migrations.AddField(
            model_name='mega_juego',
            name='enlacemg3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Mega'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlace_publi',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlacegd',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlacemg',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Mega'),
        ),
    ]
