# Generated by Django 2.2.6 on 2020-03-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200309_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='mega_juego',
            name='enlace_publimg',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad'),
        ),
        migrations.AddField(
            model_name='mega_juego',
            name='enlace_publimg2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad'),
        ),
        migrations.AddField(
            model_name='mega_juego',
            name='enlace_publimg3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad'),
        ),
    ]
