# Generated by Django 2.2.6 on 2020-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200309_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mega_juego',
            name='enlace_publi',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Google Drive 1'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlace_publi2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Google Drive 2'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlace_publi3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Google Drive 3'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlace_publimg',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Mega 1'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlace_publimg2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Mega 2'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlace_publimg3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace con Publicidad Mega 3'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlacegd2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 2'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlacegd3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Google Drive 3'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlacemg',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Mega '),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlacemg2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Mega 2'),
        ),
        migrations.AlterField(
            model_name='mega_juego',
            name='enlacemg3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlace Mega 3'),
        ),
    ]
